#!/bin/sh
if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

issue=`head -1 /etc/issue`
echo "${issue}" > /etc/issue
cat /etc/issue-std >> /etc/issue
echo "" >> /etc/issue
address=`/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print $2 }' | awk -F: '{ print $2 }'`
echo "        To manage this machine please browse http://${address}/iso" >> /etc/issue

exit 0
